"""EP03 (hospital) Field browser smoke test. Requires Python Playwright and Chromium plus the Express server:
    npm start   then   python tests/ep03_browser_smoke.py
Uses isolated browser storage and the production FieldCore.step clock. FieldEP03Data.random(name) is pinned so the wristband,
part, surgery date and visit schedule are deterministic. No real save is read or changed.
"""
import os
import re
from pathlib import Path
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
BASE = os.environ.get('FIELD_TEST_URL', 'http://127.0.0.1:3000')
STORY_KEY = 'yuyeon98.save.v1'
RED, YELLOW, BLUE = 0.1, 0.5, 0.9


def norm(text):
    return re.sub(r'[\s\-·\.\,:\[\]■※\(\)“”"]', '', text)


def run():
    with sync_playwright() as p:
        browser = p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH', '/usr/bin/chromium'),
                                    headless=True, args=['--no-sandbox'])
        page = browser.new_context(viewport={'width': 1280, 'height': 900}).new_page()
        errors = []
        page.on('pageerror', lambda error: errors.append(str(error)))
        page.goto(BASE + '/?devunlock=0', wait_until='load')
        page.evaluate("document.getElementById('darkweb-terminal').style.display='none'; document.getElementById('darkweb-overlay').style.display='block'; confirmDarkWebWarning(); closeDarkWebReadme();")

        def click(id): page.locator('#' + id).click()
        def has(id): return page.locator('#' + id).count() > 0
        def state(): return page.evaluate('FieldCore.get()')
        def data(): return state()['data']
        def sysd(): return data()['sys']
        def log_text(): return page.locator('#field-log').inner_text()
        def buttons(): return [b.inner_text() for b in page.locator('#f3-actions button').all()]
        def step(seconds): page.evaluate('(n) => { const s = FieldCore.get(); let left = n; while (left > 0 && s.status === "active") { FieldCore.step(Math.min(.5, left)); left -= .5; } }', seconds)
        def jump(day, clock):
            page.evaluate("([day, clock]) => { const d = FieldCore.get().data; d.day = day; d.clock = clock; d.sys.firstDone = true; }", [day, clock])
        def setd(**values): page.evaluate("(v) => Object.assign(FieldCore.get().data, v)", values)
        def fresh(force=None):
            page.evaluate("(force) => { window.__force = force || {}; FieldEP03Data.random = name => (name in window.__force ? window.__force[name] : 0.5); FieldUI.close(); FieldUI.open(); }", force or {})
            click('field-dispatch-new-EP03' if has('field-dispatch-new-EP03') else 'field-dispatch-EP03')
            assert state()['status'] == 'active' and data()['day'] == 1
        def force(**values): page.evaluate("(v) => Object.assign(window.__force, v)", values)
        def dead(code):
            s = state(); assert s['status'] == 'dead' and data()['failCode'] == code and s['reason'].startswith(code), (code, s['status'], data()['failCode'], s['reason'])
        def prepared_room():
            click('f3-look'); assert has('f3-laxative')
        def to_lounge_and_buy(cell='1-3'):
            click('f3-out'); click('f3-go-lounge'); click('f3-machine'); click('f3-insert'); click('f3-insert')
            click(f'f3-cell-{cell}')
        def go_visit():
            if has('f3-out'): click('f3-out')
            click('f3-go-visit')

        story_before = page.evaluate(f"localStorage.getItem('{STORY_KEY}')")
        # --- 0. Rule document: one canon (transcript -> 3화.txt -> Story window -> Field tab) -------------------------------
        story_doc = page.evaluate("document.querySelector('#darkwebReportWindowEP3 textarea').value").replace('\r\n', '\n').strip()
        txt = (ROOT / '3화.txt').read_text(encoding='utf-8').replace('\r\n', '\n').strip()
        assert story_doc == txt, 'index.html Story window must equal 3화.txt'
        transcript = (ROOT / 'docs/transcripts/reviewed/EP03_베리_해피_종합병원.txt').read_text(encoding='utf-8-sig')
        body = '\n'.join(line for line in transcript.splitlines() if line.strip() and not re.match(r'^\d\d:\d\d$', line.strip()) and not line.startswith('[') and 'generated by AI' not in line)
        for marker in ['[0] 개요 / 현황', '[1] 기본 수칙', '[2] 확인된 비정상 상황 및 대응 지침', '■ 인식표 대응', '■ 비상 상황 A', '■ 비상 상황 B', '[!] 최종 경고', '문서 번호: 2023-063호', '2024년 2차 개정', '10만원권을 일주일 동안 소지', '특별 관리실에서 꿰매진 것', '면회 요원', '병실 화폐 잔량', '대뇌의 일부분', '치사량의 합성 펜타닐 화합물', '베리 정신병원', '각 병동 1층 면회실', '입원실에 구치된 마취제', '잠든 환자는 야간, 어... 대상에서 제외됩니다.', '마음에 안 드는 환자가 있다면 해당 환자의 호출벨을 눌러 주십시오.', '보라맛 요정 주스']:
            assert marker in txt, marker
        for forbidden in ['0635', '병원관리', '메리', '시행 일자', '부착 위치', '외부 게시 불가', '서울교통공사', '병원 주소']:
            assert forbidden not in txt, forbidden
        assert '야간, 어...' in transcript and '야간, 어...' in txt
        assert page.evaluate("EPISODE_DOCS[3]") == '2023-063호'
        assert page.evaluate("CLUES.filter(c => c.ep === 3).every(c => document.querySelector('#darkwebReportWindowEP3 textarea').value.includes(c.quote))")
        assert page.evaluate("MESSENGER_GENERIC.hq.filter(m => m.ep === 3).every(m => document.querySelector('#darkwebReportWindowEP3 textarea').value.includes(m.quote))")
        assert '메리 정신병원' not in page.evaluate("document.documentElement.innerHTML") and '메리 정신병원' not in (ROOT / 'app.js').read_text(encoding='utf-8')
        print('PASS 0 rule document: the manual keeps its game-critical phrases and every Story quote from 3화.txt; Story window == 3화.txt; "야간, 어..." kept; 베리 정신병원; no unsourced metadata; clue quotes valid')

        # --- 1. Unlock -------------------------------------------------------------------------------------------------
        click('field-open')
        assert page.locator('#field-dispatch-EP03').is_disabled() and page.locator('#field-dispatch-EP03').inner_text() == '연결 제한'
        page.evaluate("FieldSave.clear('EP01', { patrols: {}, elapsed: 720, injuries: [] }); FieldSave.clear('EP02', { patrols: {}, elapsed: 700, injuries: [] }); FieldUI.close(); FieldUI.open()")
        assert page.locator('#field-dispatch-EP03').inner_text() == '파견 가능' and not page.locator('#field-dispatch-EP03').is_disabled()
        assert page.locator('#field-dispatch-EP04').inner_text() == '연결 제한'
        fresh({'band': RED})
        print('PASS 1 EP03 locked until EP02 clear, then dispatchable')

        # --- UI: minimal HUD, situational actions, status = only what was checked -------------------------------------------
        hud = page.locator('.field-hud').inner_text()
        assert 'DAY 1' in hud and '07:00' in hud and '병실' in hud
        assert buttons() == ['주변을 살핀다', '오른손 팔목을 확인한다', '병실 문 옆 차트를 확인한다', '서랍을 확인한다', '병실 밖으로 나간다'], buttons()
        visible = page.locator('#f3-scene').inner_text() + page.locator('.field-hud').inner_text() + page.locator('#f3-status').inner_text()
        for secret in ['빨간', '노란', '파란', '설사약', '마취제', '알약', '호출벨', '수술', '자판기', '요정', '10만원권 지폐', '간호사']:
            assert secret not in visible, secret
        status = page.locator('#f3-status').inner_text()
        assert '인식표: 확인하지 않음' in status and '차트: 확인하지 않음' in status and '서랍: 확인하지 않음' in status and status.count('\n') <= 4
        click('f3-look'); assert {'설사약을 복용한다', '빨간 알약을 복용한다', '침상 옆 호출벨을 누른다'} <= set(buttons()) and len([b for b in buttons() if b.startswith('마취제를')]) == 4
        click('f3-wrist'); assert '빨간색 인식표' in log_text() and '빨간색' in page.locator('#f3-status').inner_text()
        click('f3-drawer'); assert '10만원권 지폐 6장' in log_text() and '6장' in page.locator('#f3-status').inner_text()
        assert 'f3-pay-nurse' not in [b.get_attribute('id') for b in page.locator('#f3-actions button').all()]
        print('PASS UI: HUD = DAY/time/place only; no answer buttons or hidden state at start; actions and status appear only after observing')

        # --- 4. Wristbands ---------------------------------------------------------------------------------------------
        # red: laxative then complain; no pill -> false complaint; accept/timeout -> mutation, surgery moved to next day
        fresh({'band': RED}); prepared_room(); click('f3-laxative'); step(61)
        assert has('f3-complain') and has('f3-eat') and sysd()['nurse'] == 'meal'
        click('f3-complain'); d = data(); assert state()['status'] == 'active' and not d['mutated'] and d['surgeryDay'] == 5 and '강요하지 않은 채' in log_text()
        fresh({'band': RED}); prepared_room(); step(61); click('f3-complain'); dead('SPECIAL_ROOM')
        fresh({'band': RED}); prepared_room(); step(61); click('f3-eat'); d = data()
        assert d['mutated'] and d['surgeryDay'] == 2 and '보라색' in log_text() and state()['status'] == 'active' and '신체 변이' in ' '.join(d['injuries'])
        fresh({'band': RED, 'surgeryDay': 0.95}); step(61); step(16); d = data(); assert d['mutated'] and d['surgeryDay'] == 2
        # yellow: anesthetic into the marked part; hammer; pain -> hourly fall test
        fresh({'band': YELLOW, 'part': 0.1}); click('f3-wrist'); assert '표기된 부위: 오른쪽 팔' in log_text()
        click('f3-look'); click('f3-inject-0'); step(61)
        assert state()['status'] == 'active' and not data()['painShown'] and '망치' in log_text() and '아프지 않다' in log_text(); step(40); assert state()['status'] == 'active'
        fresh({'band': YELLOW, 'part': 0.1}); click('f3-look'); click('f3-inject-1'); step(61)
        assert data()['painShown'] and sysd()['fallAt'] == 480 and state()['status'] == 'active'; step(10); dead('FALL_TEST')
        fresh({'band': YELLOW, 'part': 0.1}); step(61); assert data()['painShown']; step(10); dead('FALL_TEST')
        # blue: red pill before the first position change; other bands must not take it
        fresh({'band': BLUE}); click('f3-look'); click('f3-redpill'); assert data()['tookRedPill']; step(61); step(14)
        assert state()['status'] == 'active' and sysd()['mattress'] and '매트리스' in log_text()
        fresh({'band': BLUE}); step(61); step(14); dead('BLUE_JOINTS')
        fresh({'band': RED}); click('f3-look'); click('f3-redpill'); dead('PILL_MISUSE')
        fresh({'band': YELLOW}); click('f3-look'); click('f3-redpill'); dead('PILL_MISUSE')
        print('PASS bands: red laxative/complaint/false complaint/mutation; yellow anesthetic part/hammer/fall test; blue red pill; wrong-band red pill is fatal')

        # --- 5-6. Chart and rounds -------------------------------------------------------------------------------------
        fresh({'surgeryDay': 0.5, 'surgeryTime': 0}); click('f3-chart')
        assert 'DAY 5 15:00' in log_text() and 'DAY 5 15:00' in page.locator('#f3-status').inner_text() and data()['seenSurgeryDay'] == 5
        jump(1, 509.7); step(1); assert sysd()['rounds'] == 'ask' and {'“조금씩 나아지고 있습니다.”라고 답한다', '“아픕니다.”라고 답한다', '“다 나았습니다.”라고 답한다'} <= set(buttons())
        click('f3-answer-better'); assert data()['surgeryDay'] == 5 and state()['status'] == 'active'
        jump(2, 509.7); step(1); click('f3-answer-pain'); assert data()['surgeryDay'] == 4 and '앞당겨졌다' in log_text()
        jump(3, 509.7); step(1); click('f3-answer-pain'); assert data()['surgeryDay'] == 4   # never earlier than tomorrow
        jump(3, 509.7); step(1); click('f3-answer-cured'); dead('BERRY_PSYCH')
        fresh(); jump(3, 509.7); step(1); step(15); assert sysd()['rounds'] == '' and state()['status'] == 'active' and data()['surgeryDay'] == 5
        print('PASS chart/rounds: date shown only after checking; "조금씩 나아지고 있습니다."; pain moves the date up (not before tomorrow); cure claim = 베리 정신병원')

        # --- 7. Bell ---------------------------------------------------------------------------------------------------
        fresh({'band': RED}); click('f3-look'); click('f3-bell'); d = data()
        assert d['emergencyAt'] > d['clock'] and '응급 수술 대상' in log_text() and state()['status'] == 'active'
        step(90); dead('SURGERY_WITHOUT_PREP')
        print('PASS call bell: own bell = emergency-surgery state first; unprepared surgery ends the run')

        # --- 8. Money / lights-out / night nurse ------------------------------------------------------------------------
        fresh(); jump(1, 1299.5); step(1); assert sysd()['night'] == 'sound' and {'눈을 감는다'} <= set(buttons()) and not has('f3-pay-nurse')
        click('f3-eyes'); assert '규칙적인 숨소리를 낸다' in buttons(); click('f3-breathe'); step(1); assert sysd()['night'] == 'asleep'
        step(8); assert sysd()['night'] == 'done' and data()['money'] == 6 and state()['status'] == 'active' and '야간, 어...' in txt
        fresh(); jump(1, 1299.5); step(1); step(9); assert sysd()['night'] == 'spoke' and has('f3-pay-nurse')
        click('f3-pay-nurse'); assert data()['money'] == 5 and sysd()['night'] == 'done'
        fresh(); jump(1, 1299.5); step(1); step(9); step(11); dead('NIGHT_NURSE')
        fresh(); jump(1, 1299.5); setd(money=0); step(1); step(9); click('f3-pay-nurse'); dead('NIGHT_NURSE')
        fresh({'nightWalk': 0}); jump(1, 1270); click('f3-out'); assert sysd()['night'] == 'spoke' and '소등 이후' in log_text()
        fresh({'nightWalk': 0.99}); jump(1, 1270); click('f3-out'); assert sysd()['night'] == '' and data()['loc'] == 'corridor'
        fresh(); jump(1, 1299.5); click('f3-eyes'); click('f3-breathe'); step(1); step(3); click('f3-eyes'); step(0.5); assert sysd()['night'] == 'spoke'
        print('PASS lights-out: eyes closed + regular breathing = no encounter; nurse speaks = one 10만원권; none = fail; leaving bed after 21:00 can meet the nurse')

        # --- 10. Emergency A -------------------------------------------------------------------------------------------
        def vend_prepare(force_cell='1-3'):
            fresh({'surgeryDay': 0, 'surgeryTime': 0}); click('f3-chart'); assert 'DAY 2 15:00' in log_text()
            to_lounge_and_buy(force_cell)
        vend_prepare()
        assert data()['money'] == 4 and data()['juice'] == 'bed' and has('f3-outlet') and '보라맛 요정 주스' in page.locator('#f3-scene').inner_text()
        assert page.locator('#f3-scene').inner_text().count('음료 · 음료 · 보라맛 요정 주스 · 음료') == 1
        click('f3-back'); assert '침대 위에 음료' in log_text(); click('f3-take-drink'); assert data()['juice'] == 'held'
        jump(2, 864); setd(day=2); step(1.6); d = data(); assert d['surgeryTime'] - d['clock'] <= 35 and d['surgeryTime'] - d['clock'] >= 25, d['clock']
        click('f3-drink'); assert data()['drinkOk'] and has('f3-stomach'); click('f3-stomach'); step(14)
        d = data(); assert state()['status'] == 'active' and d['surgeries'] == 1 and d['surgeryDay'] == 5 and '무작위 장기 적출술' in ' '.join(d['injuries']) and '장기 적출술' in log_text()
        click('f3-chart'); assert 'DAY 5' in log_text()   # next surgery 3 days later
        # failures: outlet, wrong cell, drink too early, no complaint
        vend_prepare(); click('f3-outlet'); dead('VENDING_OUTLET')
        vend_prepare('2-4'); d = data(); assert d['juice'] == 'none' and d['money'] == 4 and '돌려받지 못했다' in log_text()
        vend_prepare(); click('f3-back'); click('f3-take-drink'); jump(2, 800); click('f3-drink'); assert not data()['drinkOk']; click('f3-stomach'); jump(2, 897); step(2); dead('SURGERY_WITHOUT_PREP')
        vend_prepare(); click('f3-back'); click('f3-take-drink'); jump(2, 868); click('f3-drink'); assert data()['drinkOk']; step(14); dead('SURGERY_WITHOUT_PREP')
        fresh({'surgeryDay': 0}); click('f3-out'); click('f3-go-lounge'); click('f3-machine'); click('f3-insert'); assert not has('f3-cell-1-3')   # two bills in order
        print('PASS emergency A: vending machine row 1 col 3, two bills, outlet is fatal, drink 30 minutes before, stomach complaint, organ removal, next surgery +3 days')

        # --- 11. Emergency B: visitors ---------------------------------------------------------------------------------
        VIS = {'realDay': 0.5, 'fake1': 0, 'fake2': 0, 'fakeKind1': 0.1, 'fakeKind2': 0.9, 'surgeryDay': 0.99}   # fake ask d3, fake wrong d4, real d6
        def fresh_visit():
            fresh(VIS); setd(surgeryDay=9)
        def at_visit(day):
            jump(day, 655); step(1)
            assert sysd()['visitNow'] and '면회가 왔다' in log_text()
            go_visit(); assert data()['loc'] == 'visit'
        fresh_visit(); at_visit(3); assert not has('f3-end-visit') and not has('f3-follow') and not has('f3-tell')
        click('f3-listen'); assert '본부 요원입니다' in log_text() and '안내문' in log_text()
        click('f3-under'); assert has('f3-end-visit') and '녹색의 면회 종료 버튼' in log_text()
        click('f3-end-visit'); assert state()['status'] == 'active' and not data()['leak'] and data()['loc'] == 'corridor' and sysd()['visitNow'] is None
        fresh_visit(); at_visit(3); click('f3-listen'); click('f3-follow'); dead('FAKE_VISITOR')
        fresh_visit(); at_visit(4); click('f3-listen'); wrong_line = log_text().split('\n')[-1]
        p = data()['profile']; correct = f"나이는 {p['age']}, 직업은 {p['job']}, 거주지는 {p['home']}, 가족은 {p['family']}이시죠"
        assert correct not in wrong_line and '이시죠' in wrong_line; click('f3-follow'); dead('FAKE_VISITOR')
        # told info must be reported before following the real guardian
        fresh_visit(); at_visit(3); click('f3-listen'); click('f3-tell'); assert data()['leak'] and has('f3-report')
        click('f3-back'); click('f3-report'); assert not data()['leak'] and '본부에 보고' in log_text()
        fresh_visit(); at_visit(3); click('f3-listen'); click('f3-tell'); assert data()['leak']
        at_visit(6); click('f3-listen'); click('f3-follow'); assert state()['status'] == 'active' and '먼저 본부에 보고' in log_text()
        click('f3-report'); assert not data()['leak']; click('f3-follow'); assert state()['status'] == 'cleared'
        # real guardian: facts match, no personal-data request; pressing end sends them away until tomorrow; day 7 missed = failure
        fresh_visit(); at_visit(6); click('f3-listen'); real_line = log_text().split('\n')[-1]
        assert correct in real_line and '안내문' not in real_line and '본부 요원' not in real_line
        click('f3-under'); click('f3-end-visit'); assert state()['status'] == 'active' and {'day': 7, 'kind': 'real'} in sysd()['visits']
        at_visit(7); click('f3-listen'); click('f3-under'); click('f3-end-visit'); jump(7, 1379.5); step(1); dead('RESCUE_MISSED')
        # surgery eve: the guardian cannot take the patient out before the scheduled surgery
        fresh(VIS); setd(surgeryDay=7); at_visit(6); click('f3-listen'); click('f3-follow')
        assert state()['status'] == 'active' and sysd()['waitSurgery'] and '수술을 마친 후에야 병원을 나갈 수 있다' in log_text()
        click('f3-out'); click('f3-go-lounge'); click('f3-machine'); click('f3-insert'); click('f3-insert'); click('f3-cell-1-3'); click('f3-back'); click('f3-take-drink')
        jump(7, 868); setd(day=7, surgeryTime=900); click('f3-drink'); click('f3-stomach'); step(14)
        assert state()['status'] == 'cleared' and '수술 후' in log_text() and data()['surgeries'] == 1
        print('PASS emergency B: 1st-floor visiting room, green button under the table, info-requesting visitor refused, told info must be reported, real guardian by facts, surgery eve blocks leaving')

        # --- 19. Progression + Story isolation ------------------------------------------------------------------------
        assert page.evaluate("FieldSave.get().cleared.includes('EP03') && FieldSave.unlocked('EP04')")
        assert page.evaluate("FieldSave.get().records.EP03.elapsed") > 0 and '남은 10만원권' in log_text()
        click('field-list'); assert page.locator('#field-dispatch-EP04').inner_text() == '파견 가능' and not page.locator('#field-dispatch-EP04').is_disabled()  # EP04 is implemented now
        assert page.evaluate(f"localStorage.getItem('{STORY_KEY}')") == story_before, 'Story save must be untouched'
        assert page.evaluate("!FieldSave.get().cleared.includes('EP04') && AuthorRoute.get().unlocked === false && !FieldSave.get().progress")
        print('PASS progression: EP03 clear -> EP04 unlock only in Field; Story save byte-identical; progress cleared on clear')

        # --- 25. Save / resume -----------------------------------------------------------------------------------------
        fresh({'band': YELLOW}); jump(1, 1299.5); step(1); step(9); click('f3-pay-nurse'); click('f3-drawer'); click('f3-wrist')
        before = data(); assert before['money'] == 5 and before['seenMoney'] == 5
        saved = page.evaluate("FieldSave.get().progress.EP03"); assert saved['money'] == 5 and saved['day'] == 1
        assert page.evaluate("FieldSave.exportProgress().progress.EP03.money") == 5 and page.evaluate('GameSave.exportCode().length') > 0
        page.reload(wait_until='load')
        page.evaluate("document.getElementById('darkweb-terminal').style.display='none'; document.getElementById('darkweb-overlay').style.display='block'; confirmDarkWebWarning(); closeDarkWebReadme(); FieldUI.open();")
        assert page.locator('#field-dispatch-EP03').inner_text() == '이어서 파견' and has('field-dispatch-new-EP03')
        click('field-dispatch-EP03'); after = data()
        assert after['money'] == 5 and after['day'] == 1 and after['seenMoney'] == 5 and after['band'] == before['band'] and after['seenBand'] and '[복원]' in log_text()
        assert abs(after['clock'] - before['clock']) < 5 and page.locator('#f3-status').inner_text().count('5장') == 1
        page.evaluate("FieldEP03Data.random = () => 0.5"); setd(money=0); jump(1, 1299.5); step(1); step(9); step(11); dead('NIGHT_NURSE')
        assert page.evaluate("!FieldSave.get().progress") and page.evaluate("FieldSave.get().deaths.EP03") >= 1
        page.reload(wait_until='load')
        assert page.evaluate("FieldSave.get().cleared.includes('EP03') && FieldSave.unlocked('EP04')") and page.evaluate(f"localStorage.getItem('{STORY_KEY}')") == story_before
        print('PASS save: mid-run snapshot (day/clock/money/seen facts) restores after reload; death clears it; v5 export carries it; clear/deaths/EP04 unlock persist')

        # --- 26. AUTHOR hooks (no content) -----------------------------------------------------------------------------
        page.evaluate("document.getElementById('darkweb-terminal').style.display='none'; document.getElementById('darkweb-overlay').style.display='block'; confirmDarkWebWarning(); closeDarkWebReadme();")
        page.evaluate('''() => { window.__hooks = []; const add = FieldCore.hooks.add;
            add('onEpisodeStart', id => window.__hooks.push('start:' + id)); add('onMajorEvent', (id, e) => window.__hooks.push(id + ':' + e));
            add('onEpisodeClear', id => window.__hooks.push('clear:' + id)); add('onMajorEvent', () => { throw new Error('hooks must never break play'); }); }''')
        page.evaluate("FieldUI.open()"); fresh_visit(); at_visit(6); click('f3-listen'); click('f3-follow')
        seen = page.evaluate('window.__hooks')
        assert state()['status'] == 'cleared' and 'start:EP03' in seen and 'clear:EP03' in seen and 'EP03:RESCUE' in seen and 'EP03:ROUNDS' in seen or 'EP03:RESCUE' in seen, seen
        print('PASS AUTHOR hooks fire for EP03 (ids only), never affect play')
        assert not errors, errors
        browser.close()


if __name__ == '__main__':
    run()
