"""EP04 (elevator / mirror observation puzzle) Field browser smoke test. Requires Python Playwright and Chromium plus the Express server:
    npm start   then   python tests/ep04_browser_smoke.py
Uses isolated browser storage and the production FieldCore.step clock. FieldEP04Data.random(name) is pinned so the start floor,
her side, descent width, event kind, passenger talk and the C cue are deterministic (a string returned for 'eventKind' forces that
situation). No real save is read or changed.
"""
import os
import re
from pathlib import Path
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
BASE = os.environ.get('FIELD_TEST_URL', 'http://127.0.0.1:3000')
STORY_KEY = 'yuyeon98.save.v1'


def norm(text):
    return re.sub(r'[\s\-·\.\,:\[\]■※\(\)“”"]', '', text)


def run():
    with sync_playwright() as p:
        browser = p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH', '/usr/bin/chromium'),
                                    headless=True, args=['--no-sandbox'])
        page = browser.new_context(viewport={'width': 1280, 'height': 900}).new_page()
        errors = []
        page.on('pageerror', lambda error: errors.append(str(error)))

        def boot():
            page.goto(BASE + '/?devunlock=0', wait_until='load')
            page.evaluate("document.getElementById('darkweb-terminal').style.display='none'; document.getElementById('darkweb-overlay').style.display='block'; confirmDarkWebWarning(); closeDarkWebReadme();")

        boot()

        def click(id): page.locator('#' + id).click()
        def has(id): return page.locator('#' + id).count() > 0
        def state(): return page.evaluate('FieldCore.get()')
        def data(): return state()['data']
        def log_text(): return page.locator('#field-log').inner_text()
        def action(name, value=None): page.evaluate('([n, v]) => FieldCore.action(n, v)', [name, value])
        def step(seconds): page.evaluate('(n) => { const s = FieldCore.get(); let left = n; while (left > 0 && s.status === "active") { FieldCore.step(Math.min(.5, left)); left -= .5; } }', seconds)
        def setd(**values): page.evaluate("(v) => Object.assign(FieldCore.get().data, v)", values)
        def labels(): return set(b.inner_text() for b in page.locator('#f4-actions button').all())
        def fresh(force=None):
            page.evaluate("""(force) => { window.__force = force || {};
                FieldEP04Data.random = name => (name in window.__force ? window.__force[name] : (name === 'event' ? 0.99 : 0.5));
                FieldEP04Data.tuning.memoryBy = 99;   // the pacing guarantee is tested on its own below
                FieldUI.close(); FieldUI.open(); }""", force or {})
            click('field-dispatch-new-EP04' if has('field-dispatch-new-EP04') else 'field-dispatch-EP04')
            assert state()['status'] == 'active' and data()['arrivals'] == 0
        def dead(code):
            s = state(); assert s['status'] == 'dead' and data()['failCode'] == code and s['reason'].startswith(code), (code, s['status'], data()['failCode'], s['reason'])
        def ride(floor, side, last=0, **force):
            fresh(force); setd(floor=floor, side=side, lastFloor=last)
        def go(n):
            """Press a floor button and let the elevator arrive (the doors open on arrival)."""
            action('press', n); step(2)
        def close_doors(): step(7)
        def hold_down(selector):
            box = page.locator(selector).bounding_box(); page.mouse.move(box['x'] + 6, box['y'] + 6); page.mouse.down()

        story_before = page.evaluate(f"localStorage.getItem('{STORY_KEY}')")
        # --- 0. Rule document: one canon (transcript -> 4화.txt -> Story window -> Field panel) -----------------------------
        story_doc = page.evaluate("document.querySelector('#darkwebReportWindowEP4 textarea').value").replace('\r\n', '\n').strip()
        txt = (ROOT / '4화.txt').read_text(encoding='utf-8').replace('\r\n', '\n').strip()
        assert story_doc == txt, 'index.html Story window must equal 4화.txt'
        transcript = (ROOT / 'docs/transcripts/reviewed/EP04_불_꺼진_13층_엘리베이터.txt').read_text(encoding='utf-8-sig')
        body = '\n'.join(line for line in transcript.splitlines() if line.strip() and not re.match(r'^\d\d:\d\d$', line.strip()) and not line.startswith('[') and 'generated by AI' not in line)
        for marker in ['[0] 개요 / 현황', '[1] 기본 수칙', '[2] 확인된 비정상 상황 및 대응 지침', '■ 상황 A', '■ 상황 B', '■ 상황 C', '■ 상황 D', '■ 상황 E', '[!] 최종 경고', '문서 번호: 2026-013호', '신도림 만수오피스텔', '오전 4시 40분경', '후면 전체가 거울', '끝없이 반복되는 상의 통로', '네 발로 기어', '숫자는 20입니다', '현재 층보다 위층의 버튼', '1층에서는 반드시 정차합니다', '불 꺼진 빈 복도', '세 번 두드린 후 귀를 막고', '문 열림 버튼을 누른 채로', '두 걸음 가까워집니다', '3초간 꾹 누르십시오', '피 묻은 옷가지와 소지품', '전국 엘리베이터 수십 곳에 신체 일부', 'B급 정신 치료 시설', '기억 제거 수술']:
            assert marker in txt, marker
        for forbidden in ['승강기관리', '2016', '0135', '시행 일자', '부착 위치', '외부 게시 불가', '열람 금지', '오피스텔관리국', '불꺼진', '신도림 만수 오피스텔', '병원', '서울교통공사',
                          '주소', '보안 등급', '담당 부서', '층수 범위']:
            assert forbidden not in txt, forbidden
        assert page.evaluate("EPISODE_DOCS[4]") == '2026-013호'
        assert page.evaluate("CLUES.filter(c => c.ep === 4).every(c => document.querySelector('#darkwebReportWindowEP4 textarea').value.includes(c.quote))")
        assert page.evaluate("MESSENGER_GENERIC.hq.filter(m => m.ep === 4).every(m => document.querySelector('#darkwebReportWindowEP4 textarea').value.includes(m.quote))")
        print('PASS 0 rule document: the manual keeps its game-critical phrases and every Story quote from 4화.txt; Story window == 4화.txt; doc no. 2026-013호; no unsourced metadata; clue quotes valid')

        # --- 1. Unlock ------------------------------------------------------------------------------------------------
        click('field-open')
        assert page.locator('#field-dispatch-EP04').is_disabled() and page.locator('#field-dispatch-EP04').inner_text() == '연결 제한'
        page.evaluate("FieldSave.clear('EP01', { patrols: {}, elapsed: 720, injuries: [] }); FieldSave.clear('EP02', { patrols: {}, elapsed: 700, injuries: [] }); FieldUI.close(); FieldUI.open()")
        assert page.locator('#field-dispatch-EP04').inner_text() == '연결 제한', 'EP04 stays locked until EP03 is cleared'
        page.evaluate("FieldSave.clear('EP03', { patrols: {}, elapsed: 700, injuries: [] }); FieldUI.close(); FieldUI.open()")
        assert page.locator('#field-dispatch-EP04').inner_text() == '파견 가능' and not page.locator('#field-dispatch-EP04').is_disabled()
        assert page.locator('#field-dispatch-EP05').inner_text() == '연결 제한'
        print('PASS 1 EP04 locked until EP03 clear, then dispatchable; EP05 still locked')

        # --- UI: nothing spoiled at the start -------------------------------------------------------------------------
        page.evaluate("""(() => { window.__hooks = []; const add = (kind, fn) => FieldCore.hooks.add(kind, fn);
            add('onEpisodeStart', id => window.__hooks.push(['onEpisodeStart', id]));
            add('onMajorEvent', (id, event) => window.__hooks.push(['onMajorEvent', id, event]));
            add('onEpisodeClear', id => window.__hooks.push(['onEpisodeClear', id])); })()""")
        page.evaluate("Math.random = () => 0.9")          # button lights are decoys driven by Math.random, never by the answer
        fresh()
        setd(floor=7, side='L')
        hud = page.locator('.field-hud').inner_text()
        assert '13F' in hud and '문 닫힘' in hud and '휴대폰' in hud
        assert page.locator('.field-hud > *').count() == 3, 'HUD = indicator / door / phone only'
        assert page.locator('.f4-indicator').inner_text() == '13'
        assert page.locator('#f4-actions button').count() == 0, 'no answer / event buttons at the start'
        visible = page.locator('#f4-room').inner_text() + page.locator('.field-hud').inner_text()
        for secret in ['REAL', 'LEFT', 'RIGHT', 'FLOOR', '정답', '실제', '거리', '상황', 'EVENT', '위층', '아래층', '그녀', 'true', 'false', '남은 횟수']:
            assert secret not in visible, secret
        assert '7' not in page.locator('#f4-room').inner_text(), 'the real floor is not on screen before the rear mirror is looked at'
        assert page.locator('.f4-floor.lit').count() == 0
        page.evaluate("Math.random = () => 0.1"); fresh(); assert page.locator('.f4-floor.lit').count() == 13
        page.evaluate("Math.random = () => 0.9")
        fresh()
        assert page.evaluate("FieldCore.get().data.rear === null && FieldCore.get().data.sideView.L === '' && FieldCore.get().data.sideView.R === ''")
        assert page.locator('#f4-mirror-rear').is_visible() and page.locator('#f4-mirror-left').is_visible() and page.locator('#f4-mirror-right').is_visible()
        rules = page.locator('#field-tools').inner_text()
        assert '문서 번호: 2026-013호' in rules and '■ 상황 E' in rules
        print('PASS UI: HUD = false 13 / door / phone only; no answer buttons, no real floor, no side, no distance, no event names; button lights are decoys; rules panel = Story text')

        # --- 2. The mirror loop ---------------------------------------------------------------------------------------
        ride(7, 'L')
        click('f4-mirror-rear')
        assert page.locator('.f4-num').inner_text() == '7' and '남은 횟수 20' in page.locator('.f4-cnt').inner_text(), 'the rear mirror shows the real floor and 20 on the first look'
        assert data()['lastFloor'] == 7 and data()['remaining'] == 19 and data()['side'] == 'R' and data()['dist'] == 1, 'rear look: she moves to the opposite mirror and one step closer'
        assert '[후면 거울] 거울에 비친 숫자는 7이다' in log_text()
        click('f4-mirror-rear')
        assert '남은 횟수 19' in page.locator('.f4-cnt').inner_text() and data()['remaining'] == 18 and data()['side'] == 'L' and data()['dist'] == 2
        before = {k: data()[k] for k in ['side', 'dist', 'remaining', 'floor']}
        click('f4-mirror-left'); click('f4-mirror-right')
        assert {k: data()[k] for k in before} == before, 'looking at the side mirrors never moves her'
        assert data()['sideView'] == {'L': 'her', 'R': 'none'} and data()['seenSide'] == 'L'
        assert '창백한 무언가' in log_text() and '승강기 내부의 상만' in log_text()
        ride(7, 'R'); click('f4-mirror-left'); assert data()['sideView']['L'] == 'none' and data()['dist'] == 0
        print('PASS mirrors: floor only via the rear mirror (20 first), her side only via the side mirrors, rear look = +1 step and opposite side, side look free')

        ride(12, 'R'); click('f4-mirror-rear')
        lights0 = float(page.locator('#f4-shade').evaluate('e => e.style.opacity'))
        setd(dist=10); step(.25)
        assert float(page.locator('#f4-shade').evaluate('e => e.style.opacity')) > lights0 + .3
        ride(7, 'L'); setd(dist=4); action('rear')
        assert '조명이 눈에 띄게 어두워졌다' in log_text()
        setd(dist=13); action('rear'); dead('RECORD_LOST')
        ride(7, 'L'); setd(remaining=0); action('rear'); dead('NO_COUNT')
        print('PASS approach: lights dim and noise rises with distance; light-out = record lost; count 0 = system failure (non-canon)')

        # --- 3. Direction rule ----------------------------------------------------------------------------------------
        ride(7, 'L'); go(9); assert data()['floor'] == 6 and data()['doors'] == 'open', 'LEFT + upper button -> descends'
        ride(7, 'L'); go(5); assert data()['floor'] == 8, 'LEFT + lower button -> rises'
        ride(7, 'R'); go(3); assert data()['floor'] == 6, 'RIGHT + lower button -> descends'
        ride(7, 'R'); go(9); assert data()['floor'] == 8, 'RIGHT + upper button -> rises'
        ride(7, 'R'); go(7); assert data()['floor'] == 8, 'the button of the same floor does not satisfy the condition'
        ride(12, 'R'); go(13); assert data()['floor'] == 12, 'ascents stop at the top (tuning)'
        ride(7, 'L', delta=0.0); go(9); a = data()['floor']
        ride(7, 'L', delta=0.99); go(9); b = data()['floor']
        assert a == 6 and b == 4, (a, b)
        ride(3, 'R', delta=0.99); go(1); assert data()['floor'] == 1, 'a long descent still stops at floor 1'
        assert '상승' not in log_text() and '하강' not in log_text(), 'the log never tells which way it moved'
        ride(7, 'L'); action('press', 9); assert data()['moving'] > 0; action('press', 5); assert data()['target'] == 6, 'no second press while moving'
        ride(7, 'L'); click('f4-floor-9'); step(2); assert data()['floor'] == 6, 'the panel buttons work through real pointer input'
        ride(7, 'L'); go(9); action('press', 5)
        assert data()['moving'] == 0 and data()['floor'] == 6 and '문이 열려 있어' in log_text(), 'no movement while the doors are open'
        print('PASS direction: LEFT -> upper floor descends, RIGHT -> lower floor descends, opposite rises; width varies (1..3); floor 1 always stops; no direction in the log')

        # --- 4. Floor 1: get off / pass ------------------------------------------------------------------------------
        ride(3, 'R', delta=0.99); go(1); assert data()['floor'] == 1
        click('f4-exit'); s = state(); assert s['status'] == 'cleared' and '오전 4시 40분경' in log_text() and '신도림 만수오피스텔' in log_text()
        ride(3, 'R', delta=0.99); go(1); close_doors(); assert data()['doors'] == 'closed'
        action('press', 5); dead('MISSING'); assert '실종자' in state()['reason']
        ride(3, 'R', delta=0.99); go(1); close_doors()
        hold_down('#f4-door-open'); page.mouse.up()
        assert data()['doors'] == 'open' and has('f4-exit'); click('f4-exit'); assert state()['status'] == 'cleared'
        ride(7, 'R'); go(3); click('f4-exit'); dead('EXIT_WRONG_FLOOR')
        print('PASS floor 1: arriving there stops; getting off clears; leaving without getting off = missing; the door-open button reopens; getting off elsewhere fails (system)')

        # --- 5. A: dark empty corridor ------------------------------------------------------------------------------
        A = {'event': 0, 'eventKind': 'A'}
        ride(7, 'R', last=7, **A); setd(arrivals=2); go(3)
        assert data()['ev']['t'] == 'A' and '불이 꺼진 빈 복도' in log_text() and data()['arrivals'] == 3
        assert page.locator('.f4-num').inner_text() == '' and data()['remaining'] == 20, 'facing front costs nothing'
        close_doors()
        assert data()['moving'] > 0 and data()['ev'] is None and '다시 움직인다' in log_text()
        floors = []
        for roll in (0.1, 0.9):
            ride(7, 'R', last=7, **A, autoDir=roll, autoDelta=0.0); setd(arrivals=2); go(3); close_doors(); step(2); floors.append(data()['floor'])
        assert floors == [7, 5], floors   # from floor 6: it rises or descends; which one is not fixed
        ride(7, 'R', last=7, **A); setd(arrivals=2); go(3); click('f4-mirror-rear')
        assert page.locator('.f4-num').inner_text() == '' and '얼굴' in page.locator('#f4-mirror-rear').inner_text() and data()['remaining'] == 19
        assert data()['lastFloor'] == 7, 'situation A: the floor is not confirmed (last confirmed floor is unchanged)'
        assert data()['dist'] == 1 and data()['side'] == 'L'
        print('PASS A: empty dark corridor; facing front costs nothing and the doors close; looking at the rear mirror shows her face (no floor) and spends a count; up/down afterwards is random')

        # --- 6. B: passengers ----------------------------------------------------------------------------------------
        B = {'event': 0, 'eventKind': 'B', 'talk': 0.0, 'male': 0.9}
        ride(7, 'R', last=7, **B); setd(arrivals=2); go(3)
        assert data()['ev']['t'] == 'B' and data()['aboard'] and '여러 개체가 승강기에 탑승한다' in log_text() and not has('f4-knock-left')
        close_doors(); step(.9); assert not has('f4-knock-left') and data()['ev']['talk'] == 'wait'   # doors closed 1 s ago + 0.9 s: still silent
        step(1.2); assert data()['ev']['talk'] == 'talking' and '말을 걸어온다' in log_text()
        assert {'왼쪽 거울을 두드린다', '오른쪽 거울을 두드린다', '귀를 막는다', '웅크린다', '대답한다'} <= labels()
        action('press', 2); assert data()['moving'] == 0 and '움직이지 않는다' in log_text(), 'no leaving while the passenger speaks'
        # she is on the right: knock on her mirror 3 times, cover the ears, crouch until the next stop
        click('f4-knock-right'); click('f4-knock-right'); click('f4-knock-right'); click('f4-cover'); click('f4-crouch')
        assert data()['ev']['talk'] == 'done' and data()['crouched'] and '웅크린 채' in log_text() and state()['status'] == 'active'
        assert '오른쪽 거울을 두드렸다. (3회)' in log_text()
        action('press', 2); step(2)
        assert data()['arrivals'] == 4 and not data()['crouched'] and '내린다' in log_text() and data()['floor'] == 5
        ride(7, 'R', last=7, **B); setd(arrivals=2); go(3); close_doors(); step(3.5); click('f4-answer'); dead('B_ANSWERED')
        ride(7, 'R', last=7, **B); setd(arrivals=2); go(3); close_doors(); step(3.5); click('f4-knock-left'); dead('B_WRONG_MIRROR')
        ride(7, 'R', last=7, **B); setd(arrivals=2); go(3); close_doors(); step(3.5); click('f4-knock-right'); click('f4-crouch'); dead('B_BAD_ORDER')
        ride(7, 'R', last=7, **B); setd(arrivals=2); go(3); close_doors(); step(3.5); step(46); dead('B_UNRESOLVED')
        ride(7, 'R', last=7, event=0, eventKind='B', talk=0.9, male=0.9); setd(arrivals=2); go(3); close_doors(); step(20)
        assert data()['ev']['talk'] == 'none' and page.locator('#f4-actions button').count() == 0 and state()['status'] == 'active', 'passengers that do not speak need no response'
        # her mirror changes with every rear look: after one rear look she is on the other mirror and the knocks must follow her
        ride(7, 'R', last=7, **B); setd(arrivals=2); go(3); close_doors(); click('f4-mirror-rear'); assert data()['side'] == 'L'
        step(3.5); click('f4-knock-right'); dead('B_WRONG_MIRROR')
        print('PASS B: passengers board; they speak only sometimes; no answer; knock her mirror x3 -> cover ears -> crouch until the next stop; wrong mirror / wrong order / answering / too slow = system failures')

        # --- 7. C: male entity gets off, waits one floor below ------------------------------------------------------------
        C = {'event': 0, 'eventKind': 'B', 'talk': 0.9, 'male': 0.0, 'cue': 0.0}
        ride(9, 'R', last=9, **C); setd(arrivals=2); go(8)
        assert data()['aboard'] and data()['male'] and data()['floor'] == 8
        close_doors(); go(5)
        assert data()['floor'] == 7 and data()['c2'] and '흉기를 꺼내 들고 미친 듯이 웃으며 계단' in log_text() and data()['ev'] is None
        close_doors(); go(5)
        assert data()['floor'] == 6 and data()['ev']['t'] == 'C2' and data()['doors'] == 'open', 'he is waiting on the next stop'
        step(3.2); assert '처절하게 흐느끼는 소리' in log_text(), 'stairwell sobs/bones are only noises while the doors stay open'
        step(2); assert state()['status'] == 'active' and data()['doors'] == 'open', 'doors stay open while the situation runs'
        action('door', True); assert '문 열림 버튼을 누른 채' in log_text()
        step(6); assert '뼈가 부서지는 소리' in log_text() and not data()['ev']['cued'] and state()['status'] == 'active'
        step(4); assert data()['ev']['cued'] and '[안내 방송] 기괴한 흐느낌' in log_text()
        action('door', False); assert data()['ev'] is None and state()['status'] == 'active' and '하강 절차를 진행' in log_text()
        close_doors(); action('press', 2); step(2); assert data()['floor'] == 5, 'normal descent resumes afterwards'
        # early release / never holding / real pointer hold
        ride(9, 'R', last=9, **C); setd(arrivals=2); go(8); close_doors(); go(5); close_doors(); go(5)
        action('door', True); step(3); action('door', False); dead('C_EARLY_RELEASE')
        ride(9, 'R', last=9, **C); setd(arrivals=2); go(8); close_doors(); go(5); close_doors(); go(5); step(6.2); dead('C_NO_HOLD')
        ride(9, 'R', last=9, **C); setd(arrivals=2); go(8); close_doors(); go(5); close_doors(); go(5)
        hold_down('#f4-door-open'); step(10); page.mouse.up()
        assert state()['status'] == 'active' and data()['ev'] is None, 'holding the real door button with the pointer works'
        print('PASS C: male gets off; he waits at the next stop; hold the door-open button; stairwell noises are ignored; release only after the broadcast sobs; early release / no hold = system failure')

        # --- 8. D: she is in both mirrors --------------------------------------------------------------------------
        D = {'event': 0, 'eventKind': 'D'}
        ride(7, 'L', last=7, **D); setd(arrivals=5); go(9)
        assert data()['dual'] and data()['ev'] is None and not has('f4-photo-left'), 'D is only visible once a side mirror is looked at'
        close_doors(); click('f4-mirror-left')
        assert data()['ev']['t'] == 'D' and '두 거울 모두' in log_text() and data()['sideView'] == {'L': 'her', 'R': 'her'}
        assert {'왼쪽 거울을 휴대폰으로 촬영한다', '오른쪽 거울을 휴대폰으로 촬영한다', '가만히 있는다'} <= labels()
        action('press', 3); assert data()['moving'] == 0, 'no leaving while she is in both mirrors'
        click('f4-photo-right')
        assert state()['status'] == 'active' and data()['phone'] == 'taken' and data()['ev'] is None, 'she was on the left: the opposite (right) mirror is correct'
        assert data()['sideView'] == {'L': 'her', 'R': 'none'} and '그녀가 사라졌다' in log_text() and has('f4-view-photo')
        click('f4-view-photo'); dead('D_PHOTO_VIEWED')
        ride(7, 'L', last=7, **D); setd(arrivals=5); go(9); close_doors(); click('f4-mirror-right'); click('f4-photo-left')
        dead('D_WRONG_MIRROR'); assert '수십 곳에 신체 일부' in state()['reason']
        ride(7, 'L', last=7, **D); setd(arrivals=5); go(9); close_doors(); click('f4-mirror-left'); d0 = data()['dist']; click('f4-still')
        assert state()['status'] == 'active' and data()['dist'] == d0 + 2 and data()['ev'] is None and '두 걸음 가까워졌다' in log_text() and data()['phone'] == ''
        # memory: a rear look after the last normal sighting moves her; the correct mirror follows her real position
        ride(7, 'L', last=7, **D); setd(arrivals=5, seenSide='L'); go(9); close_doors(); click('f4-mirror-rear'); assert data()['side'] == 'R'
        click('f4-mirror-left'); click('f4-photo-right'); dead('D_WRONG_MIRROR')
        ride(7, 'L', last=7, **D); setd(arrivals=5, seenSide='L'); go(9); close_doors(); click('f4-mirror-rear'); click('f4-mirror-left'); click('f4-photo-left')
        assert state()['status'] == 'active' and data()['phone'] == 'taken'
        ride(7, 'L', last=7, **D); setd(arrivals=5); go(9); close_doors(); click('f4-mirror-left'); click('f4-photo-right')
        assert data()['photoOffer']
        action('press', 3); step(2); assert not data()['photoOffer'] and data()['arrivals'] == 7
        print('PASS D: invisible until a side mirror is looked at; photograph the opposite of where she belongs (success); her real mirror = canon failure; unsure -> stay still = +2 steps; viewing the photo is forbidden; memory of rear looks matters')

        # --- 9. E: names / family voice ------------------------------------------------------------------------------
        E = {'event': 0, 'eventKind': 'E', 'voice': 0.0}
        ride(7, 'R', last=0, **E); setd(arrivals=5); click('f4-mirror-rear'); setd(side='R'); go(3)
        assert data()['floor'] == 6 and data()['lastFloor'] == 7 and data()['ev']['stage'] == 'wait', 'E needs a floor that was confirmed in the rear mirror'
        assert not has('f4-turn')
        close_doors()
        assert data()['ev']['stage'] == 'voice' and '이름을 부르는 목소리' in log_text() and '무작위로 깜빡인다' in log_text()
        assert has('f4-turn') and has('f4-answer') and page.locator('#f4-panel.f4-flicker').count() == 1
        hold_down('#f4-floor-6')
        assert state()['status'] == 'dead' and data()['failCode'] == 'E_WRONG_BUTTON'
        page.mouse.up(); assert '피 묻은 옷가지와 소지품' in state()['reason'], 'the floor you are on is not the one you confirmed last'
        fresh({**E}); setd(floor=6, lastFloor=7, side='R', arrivals=3, ev={'t': 'E', 'stage': 'voice', 'voice': 'family'})
        hold_down('#f4-floor-7'); step(1.5); page.mouse.up()
        assert data()['ev'] is not None and data()['holdFloor'] == 0 and state()['status'] == 'active', 'releasing early just resets the hold'
        page.mouse.down(); step(2.9); assert data()['ev'] is not None; step(.3); page.mouse.up()
        assert data()['ev'] is None and '비명이 터져 나오며 목소리가 끊긴다' in log_text() and '잡음만 남는다' in log_text() and state()['status'] == 'active'
        for control, code in [('f4-answer', 'E_ANSWERED'), ('f4-turn', 'E_SPEAKER')]:
            fresh({**E}); setd(floor=6, lastFloor=7, side='R', arrivals=3, ev={'t': 'E', 'stage': 'voice', 'voice': 'name'}); step(.25)
            click(control); dead(code)
            if code == 'E_ANSWERED': assert '피 묻은 옷가지와 소지품' in state()['reason']
        fresh({**E}); setd(floor=6, lastFloor=7, side='R', arrivals=3, ev={'t': 'E', 'stage': 'voice', 'voice': 'name'})
        action('press', 3); dead('E_WRONG_BUTTON')
        print('PASS E: voice + flickering lights; answering / turning to the speaker / a wrong button fail; hold the last confirmed floor for 3 s -> scream, noise returns; early release resets')

        # --- 9b. Pacing: once a run is under way, a memory event (D or E) is guaranteed ----------------------------------
        fresh({'event': 0.99}); page.evaluate("FieldEP04Data.tuning.memoryBy = 5")
        setd(floor=9, side='R', arrivals=4, lastFloor=0); go(3)
        assert data()['mem'] == 0 and data()['ev'] is None and not data()['dual'], 'no guarantee before a floor was ever confirmed (E needs one)'
        fresh({'event': 0.99}); page.evaluate("FieldEP04Data.tuning.memoryBy = 5")
        setd(floor=9, side='R', arrivals=4, lastFloor=9); go(3)
        assert data()['mem'] == 1 and (data()['dual'] or (data()['ev'] and data()['ev']['t'] == 'E')), 'a D or E event is forced'
        fresh({'event': 0.99, 'eventKind': 'D'}); page.evaluate("FieldEP04Data.tuning.memoryBy = 5")
        setd(floor=9, side='R', arrivals=4, lastFloor=9); go(3); assert data()['dual'] and data()['mem'] == 1
        close_doors(); go(2); assert data()['mem'] == 1 and not data()['dual'] and data()['ev'] is None, 'only one is guaranteed'
        print('PASS pacing: at least one memory event (D/E) per run once under way; none before a floor was confirmed; only one is forced')

        # --- 10. Whole playthrough with plain play (rear -> sides -> button) ------------------------------------------
        fresh({'event': 0.99})
        for _ in range(40):
            if state()['status'] != 'active': break
            action('rear'); d = data()
            if d['floor'] == 1:
                click('f4-exit') if has('f4-exit') else (action('door', True), action('door', False), click('f4-exit'))
                break
            click('f4-mirror-left'); click('f4-mirror-right')
            her = 'L' if data()['sideView']['L'] == 'her' else 'R'
            go(min(13, d['floor'] + 1) if her == 'L' else d['floor'] - 1); close_doors()
        assert state()['status'] == 'cleared', (state()['status'], state().get('reason'), data())
        assert page.evaluate("FieldSave.get().cleared.includes('EP04') && FieldSave.unlocked('EP05')")
        assert page.evaluate("FieldSave.get().records.EP04.elapsed") > 0 and '오전 4시 40분경' in log_text()
        click('field-list'); assert page.locator('#field-dispatch-EP05').inner_text() == '파견 가능' and not page.locator('#field-dispatch-EP05').is_disabled()  # EP05 is implemented now
        assert page.evaluate(f"localStorage.getItem('{STORY_KEY}')") == story_before, 'Story save must be untouched'
        assert page.evaluate("!FieldSave.get().cleared.includes('EP05') && AuthorRoute.get().unlocked === false && !FieldSave.get().progress")
        hooks = page.evaluate('window.__hooks')
        assert ['onEpisodeStart', 'EP04'] in hooks and ['onEpisodeClear', 'EP04'] in hooks and any(h[0] == 'onMajorEvent' and h[1] == 'EP04' for h in hooks)
        assert all(len(h) <= 3 for h in hooks), 'hooks receive ids only'
        print('PASS progression + play: rear -> sides -> button loop clears EP04 -> EP05 unlock only in Field; Story save byte-identical; AUTHOR hooks (ids only, no content)')

        # --- 11. Save: mid-run snapshot, v5 transport ------------------------------------------------------------------
        fresh({'event': 0.99}); setd(floor=7, side='L'); click('f4-mirror-rear'); click('f4-mirror-left'); go(9)
        snap = {k: data()[k] for k in ['floor', 'lastFloor', 'side', 'dist', 'remaining', 'arrivals', 'seenSide']}
        page.evaluate("FieldCore.disconnect()")   # closing the window flushes the snapshot (the clock also flushes it every ~1.5 s)
        progress = page.evaluate("FieldSave.get().progress?.EP04")
        assert progress and progress['v'] == 1 and progress['floor'] == snap['floor'] and progress['remaining'] == 19
        page.reload(wait_until='load'); boot(); click('field-open')
        assert page.locator('#field-dispatch-EP04').inner_text() == '이어서 파견' and has('field-dispatch-new-EP04')
        page.evaluate("FieldEP04Data.random = name => (name === 'event' ? 0.99 : 0.5)")
        click('field-dispatch-EP04')
        assert state()['status'] == 'active' and {k: data()[k] for k in snap} == snap and '[복원]' in log_text()
        assert data()['doorHold'] is False and data()['holdFloor'] == 0
        code = page.evaluate("GameSave.exportCode()")
        story_code = page.evaluate("GameSave.exportStoryCode()")
        page.evaluate("FieldSave.reset()"); assert page.evaluate("!FieldSave.get().progress") and not page.evaluate("FieldSave.get().cleared.length")
        assert page.evaluate("(c) => GameSave.importCode(c)", code)
        assert page.evaluate("FieldSave.get().progress?.EP04?.floor") == snap['floor'] and page.evaluate("FieldSave.get().cleared.includes('EP04')")
        assert page.evaluate("GameSave.exportStoryCode()") == story_code, 'v4 Story codec unchanged'
        page.evaluate("FieldSave.saveProgress('EP04', { v: 1, floor: 99, side: 'X', dist: -1, remaining: 5000, arrivals: 'x' })")
        fresh(); assert data()['arrivals'] == 0 and data()['floor'] in (10, 11, 12), 'a corrupt snapshot is ignored'
        print('PASS save: mid-run state (floor/last floor/side/steps/count) restores after reload; held buttons never survive; v5 export carries it; corrupt snapshots ignored; v4 Story code unchanged')

        assert not errors, errors
        browser.close()
        print('ALL EP04 CHECKS PASSED')


if __name__ == '__main__':
    run()
