// EP08 Field data. Canon order: reviewed transcript (docs/transcripts/reviewed/EP08_유성_워터파크.txt; the source states
// no document number) -> 8화.txt (rule document, shown in the Story window) -> this data. The rule document is NOT
// duplicated here: the Field reads the same text from #darkwebReportWindowEP8 (reportSelector).
// Canon facts used as rules: wave every hour on the hour and at :30 lasting 15 minutes, spa bath 15 minutes, three
// slide curves, closing broadcast at 18:00, lifeguards in red with the only whistles, HQ 0050-0200. Everything under
// `tuning`, the itinerary minutes (other than the wave/closing times), lockers/sunbeds/menu/prices and the non-canon
// failure texts is implementation tuning/presentation, NOT canon. `canonFailures` lists the codes whose text restates
// a consequence the reviewed transcript states; every other failure is a minimal "record interrupted" result.
window.FieldEP08Data = {
    id: 'EP08', title: '유성 워터파크',
    reportSelector: '#darkwebReportWindowEP8 textarea',
    // Named rolls so tests can force branches: locker (index into lockers), sunbed (index into sunbeds). Default Math.random().
    random: name => Math.random(),
    startLog: '10:00 — 유성 워터파크 입장. 안내문을 끝까지 확인하십시오.',
    clearText: '정산 완료 · 손목 밴드 반납 / 정상 퇴장 확인. EP.09 연결 권한 갱신. 다음 현장은 연결 준비 중입니다.',
    zones: {
        entrance: '입구', locker: '사물함 / 탈의실', kids: '키즈존', wave: '파도풀', spa: '온천 스파', slide: '워터 슬라이드',
        food: '푸드코트', sunbed: '선베드 / 파라솔', photo: '캐릭터 포토존', tower: '안전요원대', desk: '안내 데스크', exit: '출구'
    },
    // Fixed itinerary. `at` = minutes after 10:00 shown on the band clock. Wave stages sit on canon wave times (11:00,
    // 11:30, 12:00) and closing on 18:00; the rest are tuning.
    stages: [
        { id: 'entry', zone: 'entrance', at: 0 },
        { id: 'locker', zone: 'locker', at: 10 },
        { id: 'lockerReport', zone: 'desk', at: 20 },
        { id: 'lostChild', zone: 'kids', at: 35 },
        { id: 'lostChildReport', zone: 'desk', at: 45 },
        { id: 'aloneChild', zone: 'kids', at: 50 },
        { id: 'wave1', zone: 'wave', at: 60 },
        { id: 'wave2', zone: 'wave', at: 90 },
        { id: 'whistle', zone: 'wave', at: 120 },
        { id: 'bandFloat', zone: 'wave', at: 140 },
        { id: 'sunbed', zone: 'sunbed', at: 180 },
        { id: 'spa', zone: 'spa', at: 240 },
        { id: 'slide1', zone: 'slide', at: 300 },
        { id: 'injury', zone: 'slide', at: 310 },
        { id: 'injuryReport', zone: 'desk', at: 320 },
        { id: 'slide2', zone: 'slide', at: 340 },
        { id: 'food', zone: 'food', at: 390 },
        { id: 'photo', zone: 'photo', at: 450 },
        { id: 'closing', zone: 'wave', at: 480 },
        { id: 'retrieve', zone: 'locker', at: 490 },
        { id: 'settle', zone: 'exit', at: 500 }
    ],
    tuning: {
        breathDeadline: 3, breathHold: 6, waveLength: 6, unwetWait: 8, whistleFreeze: 3, leaveWater: 4, bandCall: 5,
        bathLength: 15, thirstAt: 6, bellExit: 3, curveGap: 2.5, slideStop: 5, broadcastLength: 6
    },
    lockers: [214, 327, 108],
    sunbeds: ['C-07', 'B-12', 'D-03'],
    menu: [{ name: '우동', price: 8000 }, { name: '핫도그', price: 5500 }],
    unordered: '주문하지 않은 맑은 국 한 그릇',
    photoPrice: 5000,
    phantomCharges: [{ label: '힐링존 추가 이용', price: 12000 }, { label: '매점', price: 8000 }],
    video: {
        idle: 'movies/ep8_idle.mp4', slide: 'movies/ep8_event_slide.mp4', food: 'movies/ep8_event_food.mp4',
        mascot: 'movies/ep8_event_mascot.mp4', exit: 'movies/ep8_event_exit.mp4'
    },
    // Presentation only: the park's wording drifts from leisure to care vocabulary that the source itself uses
    // (고객/환자, 휴식/치료). Nothing here states what the park is.
    address: stageIndex => stageIndex < 14 ? '고객 여러분' : '환자 여러분',
    text: {
        ad: '[안내] 여름엔 유성! 500년 백제의 온천 위에 세운 국내 최대 도심형 워터파크. 하루 종일 꽉 찬 꿀잼, 유성 워터파크!',
        bandOn: (locker, sunbed) => `[손목 밴드] 전자 손목 밴드를 착용했다. 사물함 ${locker}번 / 선베드 ${sunbed} 배정.`,
        wrongLocker: n => `[사물함] ${n}번 사물함은 열리지 않는다. 밴드에 배정된 번호만 열린다.`,
        ownLocker: n => `[사물함] ${n}번 사물함에 소지품을 넣고 잠갔다.`,
        lockerOpens: n => `[탈의실] 덜컥. 배정받지 않은 ${n}번 사물함 문이 스스로 열린다.`,
        holdBreath: '[탈의실] 숨을 멈췄다.',
        leftLocker: '[탈의실] 숨을 참은 채 탈의실 밖으로 나왔다. 숨을 쉬었다.',
        reported: '[안내 데스크] 신고를 접수했다. 직원이 탈의실 쪽으로 향한다.',
        lostChild: '[키즈존] 아이 하나가 울면서 엄마를 찾는다. 미아로 보인다.',
        lostChildHandover: '[안내 데스크] 미아 인계를 요청했다. 직원이 키즈존으로 향한다.',
        aloneChild: '[키즈존] 보호자 없이 혼자 있는 아이가 다가와 손을 내민다. "손 잡아 주세요."',
        childRuns: '[키즈존] "오늘 수술받는 날이 아니었니?" 아이가 금방 도망쳤다.',
        waveStart: time => `[파도풀] ${time} 정각의 파도가 몰려온다.`,
        waveStartHalf: time => `[파도풀] ${time} 파도가 몰려온다.`,
        waveEnd: '[파도풀] 파도가 물러갔다.',
        lookAround: '[파도풀] 주위를 살폈다. 모두 젖은 채 웃고 있다.',
        lookUnwet: '[파도풀] 주위를 살폈다. 모두 젖어 있는데, 한 사람만 물기 하나 없이 서 있다.',
        avert: '[파도풀] 시선을 떨구고 그 자리에 가만히 섰다.',
        unwetGone: '[파도풀] 다음 파도가 지나갔다. 젖지 않은 사람은 보이지 않는다.',
        loose: '[손목 밴드] 밴드가 헐거워진 느낌이 든다.',
        wristIn: '[손목 밴드] 조이지 않고 손목을 몸쪽으로 붙였다.',
        whistleNormal: '[파도풀] 삐익—! 후루라기 소리가 울린다.',
        freeze: '[파도풀] 즉시 동작을 멈췄다.',
        towerManned: '[안전요원대] 가장 가까운 안전 요원대에 붉은색 수영복의 안전 요원이 앉아 있다. 물놀이를 계속한다.',
        towerEmpty: '[안전요원대] 가장 가까운 안전 요원대가 비어 있다. 물가에 검은색 수영복 반바지 차림의 사람이 서 있다.',
        outOfWater: '[파도풀] 즉시 물 밖으로 나왔다.',
        bandFloats: '[파도풀] 잠시 후 다시 물에 들어갔다. 손목이 가볍다. 밴드가 저절로 풀려 물 위에 떠올랐다.',
        callLifeguard: '[파도풀] 힘껏 안전 요원을 불렀다. 붉은 수영복의 안전 요원이 달려온다.',
        newBand: (locker, sunbed) => `[안내 데스크] 손목 밴드를 재지급 받았다. 사물함 ${locker}번 / 선베드 ${sunbed} 그대로.`,
        sunbedArrive: '[선베드] 파라솔 아래 선베드가 줄지어 있다. 몇 자리는 오래 비어 있다. 수건만 놓인 자리도 있다.',
        sunbedOwn: s => `[선베드] 밴드에 표기된 ${s} 선베드에 누웠다. 휴식.`,
        broadcastNormal: who => `[안내 방송] 미아 보호자를 찾습니다. 노란 수영모를 쓴 어린이의 보호자분께서는 안내 데스크로 와 주시기 바랍니다. ${who}께서는 안전한 이용 부탁드립니다.`,
        broadcastName: '[안내 방송] "……귀하의 성함 고객님, 안내 데스크로 와 주시기 바랍니다." 분명히 내 이름이다.',
        broadcastOver: '[안내 방송] 방송이 끝났다.',
        answeredNormal: '[안내 방송] 대답했지만 아무도 신경 쓰지 않는다.',
        spaIn: '[온천 스파] 온천수에 몸을 담갔다. 1회 입욕 15분.',
        thirst: '[온천 스파] 목이 타들어 간다. 손 닿는 곳에 물이 있다.',
        endure: '[온천 스파] 마시지 않고 참았다.',
        bell: '[온천 스파] 딸랑— 안내종이 울린다.',
        spaOut: '[온천 스파] 탕에서 나왔다.',
        rideStart: '[슬라이드] 출발. 물살에 몸이 쏠린다. 곡선을 세어야 한다.',
        curve: '[슬라이드] 곡선에 진입했다. 몸이 크게 꺾인다.',
        counted: n => `[슬라이드] (${n})`,
        arrive: '[슬라이드] 도착 지점에 닿았다.',
        notNow: '[슬라이드] 물살이 강해 제대로 버티지 못했다.',
        qte: { arms: '[슬라이드] 양팔을 벌렸다.', wall: '[슬라이드] 벽면에 팔을 밀착시켰다.', slow: '[슬라이드] 속도가 줄어든다.', stop: '[슬라이드] 그 자리에 멈췄다.' },
        qteOrder: '[슬라이드] 몸이 계속 미끄러진다.',
        rescued: '[손목 밴드] 긴급 전화 버튼을 눌렀다. 구조 요청이 접수되었다. 구조되어 슬라이드를 빠져나왔다.',
        scrape: '[슬라이드] 도착하면서 무릎이 쓸려 피가 맺혔다. 흰 옷의 직원이 다가온다. "수술실로 안내해 드리겠습니다."',
        declined: '[슬라이드] 정중하게 거절했다. 직원이 물러난다.',
        injuryReported: '[안내 데스크] 부상을 접수했다. 소독을 받았다.',
        ordered: (name, price) => `[푸드코트] ${name}을 주문했다. (${price.toLocaleString()}원 결제)`,
        served: item => `[푸드코트] 음식이 나왔다. ${item}도 함께 나왔다.`,
        ateAll: '[푸드코트] 남기지 않고 전부 먹었다.',
        staffAsk: '[푸드코트] 직원이 다가와 묻는다. "언제 수술이십니까?"',
        notToday: '[푸드코트] "오늘은 아닙니다." 직원이 고개를 끄덕이고 돌아간다.',
        photoNormal: '[포토존] 캐릭터가 인솔 직원 두 명과 함께 포토존에 서 있다.',
        photoTaken: price => `[포토존] 캐릭터와 사진을 찍었다. (${price.toLocaleString()}원 결제)`,
        photoSkip: '[포토존] 사진은 찍지 않았다.',
        mascotAlone: '[포토존] 잠시 후, 같은 캐릭터가 혼자 걸어 나온다. 주변에 인솔 직원이 없다.',
        backAway: '[포토존] 등을 보이지 않은 채 인파가 많은 쪽으로 천천히 물러났다. 캐릭터가 멀어진다.',
        closing: who => `[안내 방송] 18:00 폐장 안내 방송입니다. 오늘 하루 치료를 마치신 ${who}께서는 퇴장해 주시기 바랍니다.`,
        stayAsk: '[파도풀] 아직 풀 안에 남은 사람들이 웃으며 말한다. "조금 더 놀고 가자."',
        refused: '[파도풀] 정중하게 거절했다.',
        blocked: '[파도풀] 그들이 팔을 붙잡고 앞을 막아선다.',
        emergencyBlock: '[손목 밴드] 긴급 전화 버튼을 눌렀다. 안전 요원이 다가오자 사람들이 손을 놓았다.',
        emergencyIdle: '[손목 밴드] 긴급 전화가 연결되었다. 이상 없음을 알리고 종료했다.',
        retrieved: n => `[사물함] ${n}번 사물함에서 소지품을 꺼냈다.`,
        statement: '[출구] 손목 밴드 정산 내역이 표시된다. 이용한 적 없는 결제 기록이 섞여 있다.',
        paid: total => `[출구] 표시된 금액 ${total.toLocaleString()}원을 그대로 결제했다.`,
        returned: '[출구] 손목 밴드를 반납했다.',
        notYet: '[출구] 아직 폐장 전이다. 정산은 폐장 후에 진행된다.',
        moved: zone => `[이동] ${zone}`
    },
    failures: {
        BAND_REMOVED: '퇴장 전에 손목 밴드를 풀었습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        BAND_TIGHTENED: '헐거워진 손목 밴드를 조였습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        BAND_FLOAT: '풀려 떠오른 손목 밴드를 보고도 즉시 안전 요원을 부르지 않았습니다. 손목 밴드를 재지급 받지 못했습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        LOCKER_BREATH: '배정받지 않은 사물함이 열린 탈의실에서 호흡했습니다. 고온과 전신 출혈을 반복하는 변종 에볼라 바이러스 감염 증상을 보이다 사망하는 사례가 확인되었습니다.',
        LOCKER_LOOK: '스스로 열린 사물함 안을 들여다보았습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        CHILD_HAND: '아이의 손을 잡았습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        CHILD_WORDS: '혼자 있는 아이에게 다른 말을 했습니다. 아이가 다시 손을 내밉니다. 현장 연결이 끊겼습니다. 기록 중단.',
        UNWET: '젖지 않은 사람의 흥미를 끌었습니다. 이후 체내에 있는 수분에 거부 반응을 가지게 되며 한 시간 이내에 체내의 수분을 모두 게워낸 채 발견된 사례가 확인되었습니다. 수습된 유해에서는 혈액이 검출되지 않았습니다.',
        WHISTLE_MOVE: '후루라기 소리를 듣고도 동작을 멈추지 않았습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        WHISTLE_STAY: '비어 있는 안전 요원대를 확인하고도 물에 남아 있었습니다. 검은색 수영복 반바지를 입은 안전 요원에게 심폐소생술을 받게 되며 양쪽 갈비뼈 골절 및 장기 손상을 당하는 사례가 확인되었습니다.',
        BROADCAST: '성함이 호명된 안내 방송에 응했습니다. 본 시설은 성인 고객을 안내 방송으로 호출하지 않습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        SPA_DRINK: '탕 안에서 물을 마셨습니다. 탕 안에서 수분을 섭취한 고객은 수술 대상으로 분류됩니다.',
        SPA_LATE: '안내종이 울렸는데도 탕에서 나오지 않았습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        SLIDE_END: '네 번째 곡선에서 멈추지 못하고 끝까지 내려갔습니다. 도착 지점이 아닌 지하 수술실로 이송되었으며 마취 없이 개복된 상태로 발견된 사례가 확인되었습니다. 해당 고객들의 체내에서는 혈액을 포함한 모든 수분이 제거되어 있었습니다.',
        INJURY_FOLLOW: '수술실로 안내하는 사람을 따라갔습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        FOOD_LEFT: '주문하지 않은 메뉴를 남기거나 돌려보냈습니다. 치료 프로세스에 협조하지 않는 환자들에게 인내심을 가지는 친절한 병원이 아님을 명심하여 주십시오. 현장 연결이 끊겼습니다. 기록 중단.',
        SURGERY_DATE: '"언제 수술이십니까?"라는 질문에 날짜를 특정하여 답했습니다. 해당 날짜에 반드시 수술을 받게 됨을 확인하였습니다.',
        SURGERY_OTHER: '"언제 수술이십니까?"라는 질문에 "오늘은 아닙니다." 외의 대답을 했습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        SUNBED: '비워져 있는 선베드를 이용했습니다. 퇴장하지 못하였으며 폐장 후 분실물 센터에 부위별로 분류되어 있던 사례가 확인되었습니다.',
        CHARACTER: '혼자인 캐릭터에게 섣불리 다가가거나 등을 보이며 도망치려 했습니다. 폐장 후 해당 캐릭터 내부에서 으깨진 채로 발견된 사례가 확인되었습니다.',
        CLOSING_STAY: '폐장 방송 이후 조금 더 놀고 가자는 권유에 응했습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        CLOSING_FORCE: '막아선 사람들을 힘으로 뿌리치려 했습니다. 현장 연결이 끊겼습니다. 기록 중단.',
        SETTLE_DISPUTE: '정산 내역에 이의를 제기하거나 환불을 요구했습니다. 본 시설의 결제 기록에는 오류가 발생하지 않습니다. 현장 연결이 끊겼습니다. 기록 중단.'
    },
    canonFailures: ['LOCKER_BREATH', 'UNWET', 'WHISTLE_STAY', 'SPA_DRINK', 'SLIDE_END', 'SURGERY_DATE', 'SUNBED', 'CHARACTER']
};
